const names = [
  "BRAD PITT",
  "JACKIE CHAN",
  "SCARLET JOHANSON",
  "WILL SMITH",
  "MICHAEL KEATON",
  "DENZEL WASHINGTON",
  "JOQAUIN PHOENIX",
  "ORLANDO BLOOM",
  "JENNIFER ANNISTON",
  "MONICA BELUCCI",
  "ANGELINA JOLIE",
  "JASON STATHAM",
  "TOM HOLLAND",
  "CHRIS PRATT",
  "ANDREW GARFIELD",
];

export default names;
